### ISSUE TITLE
AttributeError: '_arv.Genome' object has no attribute 'get_snp'

### ISSUE THREAD

**Issue by isviridov** [cslarsen/arv#1]
I suspect something has changed recently - can't even run example:
```
>>> genome.get_snp("rs123")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_arv.Genome' object has no attribute 'get_snp'
```

**Comment by cslarsen** [comment]
Thanks for this. Yep, I removed `get_snp`. It's now the default for getting items, so `genome["rs123"]` will fetch the SNP, while you have to do `genome["rs123"].genotype` to get the genotype. I've updated the docs.

**Comment by cslarsen** [comment]
By the way, the fix is on head, and I'll publish a new version to PyPi later.
