### ISSUE TITLE
Usage Section of Readme unclear

### ISSUE THREAD

**Issue by knowledgebaum** [cslarsen/arv#4]
**This is what is written in usage section.**  
>>> genome["rs123"]
>>> snp
<SNP: chromosome=7 position=24966446 genotype='AA'>
>>> snp.chromosome
7
>>> snp.position
24966446
>>> snp.genotype
<Genotype 'AA'>

I think you mean to put the first two statements together

>>> genome["rs123"]
>>> snp

becomes
>>>snp = genome["rs123"]

**Comment by cslarsen** [comment]
Fixed in 3999e00361f13d404d0d86d76bcedd4d8d49c393, thanks
